### ISSUE TITLE
[Mechanics] Thrower motor too high

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#10]
The motor is too high off the ground, making it inoperable.

![image](https://user-images.githubusercontent.com/5435954/194743458-2ef51786-e8b0-437e-9125-58c401a39d4b.png)

**Comment by karlrahn** [comment]
Made the thrower height-adjustable. Meaning that when you loosen the bolts, the height can be adjusted, later tightened up and set up.

**Comment by Akustav** [comment]
Interesting idea overall. But there is a issue:

It can not be lowered enough to touch the ball:
![image](https://user-images.githubusercontent.com/5435954/195380841-df68f111-1c32-4bb5-a80b-c8f49904f608.png)

The middle ramp will touch the ground before contact can be done with the ball. I suggest shortening the middle ramp a little, This stuff can be cut:

![image](https://user-images.githubusercontent.com/5435954/195381141-bb3b1efb-3560-49f1-80bb-5e5b0d468860.png)

I would suggest to set up the height of the thrower in a static way. There clearance of the robot should not change and therefor adjustability is not too important and can make the solution more fragile. If you insist on this solution, I suggest beefing up this area. Overall thicker walls there are usefull and I would add a fillet to the internal corners for extra strength:

![image](https://user-images.githubusercontent.com/5435954/195381779-0b053fef-90bd-491f-98fe-41765764549f.png)

**Comment by karlrahn** [comment]
But if i make the sliding area's lenght longer, then it should be operable ?

**Comment by Akustav** [comment]
You still need to make the small ramp shorter because the ramp can not go into the floor. With the current configuration the motor needs to go down around 13mm but the thrower is at most 12mm off the ground.

**Comment by karlrahn** [comment]
It won't go into ground, if I don't fully lower the ramp.

**Comment by karlrahn** [comment]
I can leave it to somewhere midpoint etc.

**Comment by karlrahn** [comment]
The whole configuration moves together. The motor/ramp/walls are connected to the pillars on the side. So I can move these components all together down or upwards
