### ISSUE TITLE
[Mechanics] A reason for 3 support posts?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#12]
Is there a reason to not have a support in the front of the robot? When it is asymmetrically supported it might start to bend the structure:

![image](https://user-images.githubusercontent.com/5435954/195384683-e2358b8c-f0bb-48d7-ac20-8286f322f99e.png)

**Comment by karlrahn** [comment]
I can't make the height regulator there, because it will collide with the wall & motor connections. I think that the fourth pillar isn't necessary, because the other 3 pillars are quite wide and supporting pretty well.

**Comment by karlrahn** [comment]
I can make an extension for the rear pillar on that side, maybe it will support a bit
