### ISSUE TITLE
[Mechanics] holes in the support posts should not be threaded

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#13]
Currently the holes in the support posts are threaded but you also have a nut at the end of the bolt. Is this a oversight?

![image](https://user-images.githubusercontent.com/5435954/195385317-5502675d-5292-4681-9d13-0149371c32de.png)

**Comment by karlrahn** [comment]
I made this connection different, because the bolt would've collided with the path of ball, which is why I made a cut into the the wall, so I can fit the bolt there and the nut onto the other side

**Comment by karlrahn** [comment]
Just to make it as strong as possible
