### ISSUE TITLE
[Mechanics] make whole sidewall thickness 4.8 for milling

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#14]
Currently the wall is 4.5mm. I suggest you mill the thrower sidewalls for strength and time reasons. To make it more correct I also suggest fixing the thickness of these components to be 4.8 instead of 4.5 for the whole sheet.

![image](https://user-images.githubusercontent.com/5435954/196023803-d3864dfd-ecf9-4a19-b038-06b7ebaecb5d.png)

If this makes a spacer too long, you can mill a pocket where is needed.

**Comment by karlrahn** [comment]
Increased the width.
