### ISSUE TITLE
[Mechanics] add radius to internal corners

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#15]
Add a radius to internal corners like the motor cable hole and the bottom steps of the sidewalls.

![image](https://user-images.githubusercontent.com/5435954/196023868-a42bfe7d-2e38-40ce-8378-72d548b0d0c0.png)

A mill cuts a circle and creates a radius the size of the tool in internal corners.

**Comment by karlrahn** [comment]
Added!
