### ISSUE TITLE
[Mechanics] Motor cable hole seems badly placed

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#16]
I checked the motor hole and thrower location. Currently you need to move the thrower assembly down around 9mm and this causes a situation where the hole is blocked by the top layer of the frame:

![image](https://user-images.githubusercontent.com/5435954/196024011-85a7a5a0-6371-429b-8527-204f68060bbf.png)

Is this a problem?

**Comment by karlrahn** [comment]
Fixed hole, approved by you on Monday
