### ISSUE TITLE
[Mechanics] How is the beautyrim attached

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#18]
How is the beautyrim attached to the robot? There is currently no clear indication. Since it blocks some of the mounting holes it must also be removable.

Take into consideration that it should not break on impact. I suggest integrating the beautyrims looks to the outer wheel pieces. You can also paint it, making it stick out

**Comment by karlrahn** [comment]
made a small pin which fill tightly fit into the hole on the wheel center. Just pull out or push in, no any screws or glue needed.

**Comment by Akustav** [comment]
The main issue is that if another robot hits the wheel, will it stick there? Friction fits degrade over time so it will become looser and looser over time. Is this something to worry about?

**Comment by karlrahn** [comment]
Fixed the beautyrim, actually made a new one, which is attachable with the same bolts as for the wheels
