### ISSUE TITLE
[Mechanics] Consider making the wheel mount smaller

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#19]
Consider making the wheel mount smaller. Currently it is 28 mm but maybe it can be 25 or 20 mm to make its creation process simpler and faster.

**Comment by Akustav** [comment]
Maybe it can be shortened a little as well? It makes creating it a lot simpler

**Comment by karlrahn** [comment]
I think that 8mm is enough for wheel mounts, as well I made the mount 25mm and all are already cut out. 1 thing to do is to make the holes and they'll be ready.
