### ISSUE TITLE
[Mechanics] tweaks to motor mount

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#20]
Some suggestions for the motor mount:

1. Remove the back support, it is not needed to support the back of the motor. Besides being a extra piece it can make assembly more difficult because you need to align all pieces to their corresponding holes.
2. How do you plan to manufacture the motor mounts? They can currently not be manufactured easily using 3D printing or milling.

Some ways to fix it:

- Don't have the motor at an angle, making the mounts simpler
- Have a two piece construction, where the angle is dictated by a separate mounting piece. Something like this:
![image](https://user-images.githubusercontent.com/5435954/199569854-5d95c9a6-eb32-47c4-8634-4deb82f7dab3.png)

Any other ideas are also welcome

**Comment by karlrahn** [comment]
Removed the angle, no degrees

**Comment by maidlam** [comment]
Back supports are still in the model. Do you want to keep them?

**Comment by karlrahn** [comment]
I'll leave them, the new robot will be stiffer that way

**Comment by karlrahn** [comment]
Also made the dogbones bit better on the upperplate and the motor mounts, added bolt holes under the lowerplate, to lock the  motors onto the lower plate.
