### ISSUE TITLE
[Mechanics] Camera angle adjustability

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#22]
Adjustable camera angles can be problematic to set up and maintain. When someone grabs the robot in a wrong way, the angle might shift. I suggest adding the FOV pyramid to the robots camera and based on that fix the angel so, that the upper pyramids side is parallel to the ground.

![image](https://user-images.githubusercontent.com/5435954/199571413-4df630df-5d3b-424c-bb1a-49c27346e252.png)

**Comment by karlrahn** [comment]
Made the camera with static angle
