### ISSUE TITLE
[Mechanics] Add bolt holes for thrower

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#24]
The thrower is currently friction fit in the robot - add bolts and holes for attaching the thrower.

![Fusion360_2022-11-21_12-44-15](https://user-images.githubusercontent.com/32770145/203057864-e0e39e40-5577-41d1-8db1-52282805c28b.png)

**Comment by karlrahn** [comment]
Fixed the thrower, added bolts and made a new thrower motormount because the holes could not align with the holes.

**Comment by maidlam** [comment]
Might have been a mistunderstanding - I meant add holes to the thrower walls and bottom plate so that thrower can be fixed in place.

**Comment by karlrahn** [comment]
added the bolts! Should be fixed into a position now.
