### ISSUE TITLE
[Mechanics] Thrower holes in plates have square corners

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#25]
I think Fusion 360 CAM might resolve these corners and make them round, and there doesn't seem to be any interference with the thrower at the moment, it is better to round the corners / add dogbones yourself.

![Fusion360_2022-11-21_12-45-04](https://user-images.githubusercontent.com/32770145/203057383-48cdb330-d40a-4732-8a69-3857a1116e50.png)
![Fusion360_2022-11-21_12-47-00](https://user-images.githubusercontent.com/32770145/203057397-571fa9cf-14e7-42c4-bf94-f084d3474f11.png)

**Comment by karlrahn** [comment]
Added fillets, removed sharp corners on the body parts
