### ISSUE TITLE
[Mechanics] Camera mount not mountable

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#26]
There are no mortises for the camera mount tenons and there is some interference with the plates and camera mount.

![Fusion360_2022-11-21_12-50-59](https://user-images.githubusercontent.com/32770145/203058119-ee3d5c3c-ff5b-40c1-86f2-62d3f39a9256.png)

**Comment by karlrahn** [comment]
Is mountable now, was missing the mounting holes

**Comment by karlrahn** [comment]
Also added bolt holes under the lower plate to lock it  into place.
