### ISSUE TITLE
[Mechanics] Missing PC power adapter socket cutout

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#30]
There is no cutout for the power adapter socket.

Refer here for the correct cutout
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_pc_power_adapter_socket

**Comment by karlrahn** [comment]
Added PC power adapter and socket

**Comment by maidlam** [comment]
The current cutout wont fit the power adapter socket.
Make the cutout based on this image (from mechanics guide).

![pilt](https://user-images.githubusercontent.com/32770145/204150436-8fb9bc3c-4617-4896-91b5-d9a7c28a5555.png)

**Comment by karlrahn** [comment]
Fixed the hole size!
