### ISSUE TITLE
[Mechanics] Wheel will mount incorrectly

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#32]
Currently the bolt that fixes the wheel to the motor will end up at the point where the motor shaft transitions from flat to round - the wheel will not mount correctly.
Since you haven't fully manufactured the wheel mounts, the hole can be moved closer to the wheel. There are also set screws available in case bolt heads will cause interference.

![Fusion360_2022-11-21_14-07-18](https://user-images.githubusercontent.com/32770145/203059879-01c1c5e8-23de-4103-9896-5f40b780f61f.png)

**Comment by karlrahn** [comment]
Fixed the distance of the hole, should be okay now
