### ISSUE TITLE
[Mechanics] Motor mount tenons don't have much support

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#33]
The holes for the motor mount tenons don't have much support at the shorter sides.

![pilt](https://user-images.githubusercontent.com/32770145/203060532-d2a4d4f0-8bf4-4756-b033-7b817da29cad.png)

One way to alleviate this is to adjust the dogbones of the holes in the plate and the dogbones around the tenons.
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_inside_sharp_corners

![pilt](https://user-images.githubusercontent.com/32770145/203061070-21b61ad3-3f0a-4209-b157-819e051f1ef5.png)

**Comment by karlrahn** [comment]
If I fix that, then I'm pretty sure the mounts won't move at all and the other question will be answered probably as well.

**Comment by karlrahn** [comment]
Fixed

**Comment by maidlam** [comment]
The tenons have more support now, but the dogbones for the mortises are unmillable - #45
