### ISSUE TITLE
Don't place net labels upside down

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#35]
![image](https://user-images.githubusercontent.com/1595938/204148033-09076527-a5f0-4249-a7f1-2597c3408218.png)
![image](https://user-images.githubusercontent.com/1595938/204148041-4484f9ed-65d7-4930-ac0a-97e3c502886c.png)

**Comment by incrut** [comment]
![answ](https://user-images.githubusercontent.com/113035229/204149694-e7aa962a-b639-4e4a-95cb-56f1190ef9b2.png)
Of course, I would not place the nets like that on purpose, and on my PC, it looks not turned upside down. However, for some reason, after I upload the file, it turns them this weird way.

**Comment by ReikoR** [comment]
Are you using EasyEDA and converting to Altium Designer? If that's the case, then I would like to review using EasyEDA design files. There is no point of converting the files.

**Comment by incrut** [comment]
> Are you using EasyEDA and converting to Altium Designer? If that's the case, then I would like to review using EasyEDA design files. There is no point in converting the files.

Oh yeah, sure, I just thought that you were using only Altium. Where should I send the EasyEDA file? To the electronics repository branch?

**Comment by ReikoR** [comment]
Commit and push it to `electronics` branch and `electronics` folder.
