### ISSUE TITLE
Add decoupling capacitors to microcontroller

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#38]
![image](https://user-images.githubusercontent.com/1595938/204148627-22cddebe-84dd-4f6d-b16a-50e6429e77e3.png)

Each VDD/VDDA pin should have a decoupling capacitor (typically 100nF). One additional capacitor with higher capacitance (4.7uF is recommended in the datasheet) somewhere near MCU is also recommended.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/204615586-8142efd5-b8e0-4748-88d3-879fc44c9bd6.png)

Decoupling capacitors should not be connected in series, but in parallel with VDD(A) and GND.

Also add one 4.7uF capacitor.

**Comment by incrut** [comment]
> ![image](https://user-images.githubusercontent.com/1595938/204615586-8142efd5-b8e0-4748-88d3-879fc44c9bd6.png)
> 
> Decoupling capacitors should not be connected in series, but in parallel with VDD(A) and GND.
> 
> Also add one 4.7uF capacitor.

What should be the second leg connection for the capacitors, then? One leg is connected to the VDD(A) pin of the microcontroller, and the second leg is connected to the ground?

**Comment by ReikoR** [comment]
Yes, capacitor should be between VDD(A) and GND.

> parallel with VDD(A) and GND

**Comment by incrut** [comment]
![question2](https://user-images.githubusercontent.com/113035229/204804441-eeab4d3d-3b5e-49fa-88f4-c131c457d449.png)

> Yes, capacitor should be between VDD(A) and GND.
> 
> > parallel with VDD(A) and GND

Should it look like this in the end?

**Comment by incrut** [comment]
> ![question2](https://user-images.githubusercontent.com/113035229/204804441-eeab4d3d-3b5e-49fa-88f4-c131c457d449.png)
> 
> > Yes, capacitor should be between VDD(A) and GND.
> > > parallel with VDD(A) and GND
> 
> Should it look like this in the end?

 But with the 4.7uF capacitor

**Comment by ReikoR** [comment]
Yes

**Comment by incrut** [comment]
> Yes

I uploaded the latest schematic to the electronics brunch. Hopefully, I solved all the issues there.
