### ISSUE TITLE
Missing battery input and motor driver output connectors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#39]
![image](https://user-images.githubusercontent.com/1595938/204148888-0f002c42-61ca-4fb6-9d97-067e70ea41dc.png)

Connectors or pads are needed for battery input and motor driver outputs. I recommend simple SMD pads where wires can be soldered.

**Comment by ReikoR** [comment]
SMD pads should also be added for battery input.

Reverse voltage protection should also be added:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/components.html#_reverse_voltage_protection

**Comment by ReikoR** [comment]
1. BUK6U10-30P body diode has wrong direction.
![image](https://user-images.githubusercontent.com/1595938/204882137-55a277d8-e003-45a5-9653-78efd512f2ed.png)
\
From [datasheet](https://assets.nexperia.com/documents/data-sheet/BUK6Y10-30P.pdf):
![image](https://user-images.githubusercontent.com/1595938/204882269-99795736-aeb1-48f5-a8b1-916e7e73339c.png)

2. I can't find BUK6U10-30P on the PCB. Battery input pad is connected straight to +16V.
![image](https://user-images.githubusercontent.com/1595938/204882685-8ca8e278-f875-4390-b15a-8c00d41c3175.png)

**Comment by incrut** [comment]
> 1. BUK6U10-30P body diode has wrong direction.
>    ![image](https://user-images.githubusercontent.com/1595938/204882137-55a277d8-e003-45a5-9653-78efd512f2ed.png)
>    
>    From [datasheet](https://assets.nexperia.com/documents/data-sheet/BUK6Y10-30P.pdf):
>    ![image](https://user-images.githubusercontent.com/1595938/204882269-99795736-aeb1-48f5-a8b1-916e7e73339c.png)
> 2. I can't find BUK6U10-30P on the PCB. Battery input pad is connected straight to +16V.
>    ![image](https://user-images.githubusercontent.com/1595938/204882685-8ca8e278-f875-4390-b15a-8c00d41c3175.png)

It was the initial design where I have not added reverse voltage protection yet.
