### ISSUE TITLE
[Mechanics] no assembly file with the motor chassis

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#4]
There is no chassis assembly with the thrower. This is good to have to check how it fits in the test robot.

**Comment by Akustav** [comment]
The thrower is not mated to the test chassis. It should be mounted to it properly.

**Comment by karlrahn** [comment]
Added some joints to the robot chassis. Should be okay at the moment, brought up some errors, when I tried to but joints to all ballthrower - chassis connections. I don't know is this about the design or something but in reality, it can be mounted onto the robot.
