### ISSUE TITLE
Power port rotation

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#44]
![image](https://user-images.githubusercontent.com/1595938/204150055-f168c700-a07f-470f-a99e-62ed8fb32f70.png)
![image](https://user-images.githubusercontent.com/1595938/204150070-d1a6fc6e-8e32-440e-88f4-412d1fb7fefa.png)

It would be better if GND pointed downwards and higher potential power ports pointed upwards. Sideways can be acceptable if there is not enough room.

**Comment by incrut** [comment]
Hopefully, I have solved all the issues in the latest patch.
