### ISSUE TITLE
[Mechanics] Motor mounts' and camera mount mortises' dogbones not millable

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-jackbot#45]
The dogbones for the motor mounts and camera mount mortises are not millable with a 3 mm mill.
Assuming 3 mm because the dogbones are made with 3 mm circles.

The distance between the corners of the dogbones is less than 3 mm, causing the mill to not fit through, leaving them unmilled.
The circles for the dogbones should be tangent with the sides of the mortise.

![Fusion360_2022-11-27_19-14-40](https://user-images.githubusercontent.com/32770145/204151104-1cafeff9-11f3-4e29-acac-31ecbfbc9c82.png)

**Comment by karlrahn** [comment]
Fixed the sizes and corners for milling, needs checking
