### ISSUE TITLE
No need for second support of motors

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#46]
I suggest either removing the motor back supports or make the slots for them bigger so there is a loose fit. Otherwise it is a horror show to assemble since you need to align absolutely every slot with its tab. Use as few precise alignment faces as possible

![image](https://user-images.githubusercontent.com/5435954/204153784-b1459c62-d0c2-4725-bea2-46c6948fb4a0.png)

**Comment by karlrahn** [comment]
will do!

**Comment by karlrahn** [comment]
Made the motor holder rear mount hole a bit wider

**Comment by maidlam** [comment]
The motor support slots are currently 5 mm thick (vs old 4,8 mm), length is still the same. I think they should be bigger.
And I think the bottom plate's slots shouldn't be widened, only the slots in the top plate for the motor suports.

@Akustav How much increase would you suggest for the slots?

**Comment by karlrahn** [comment]
I made both holes 0.5 mm wider now on the top plate, so that the bottom plate has 4.8mm

**Comment by Akustav** [comment]
Around 0.5mm slop should be enough to make assembly simple and still locate them well enough
