### ISSUE TITLE
Quite many spacers connecting the top and bottom plate

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#47]
You currently have quite a few spacers connecting the two halves. Are all needed? This is especially true here;

![image](https://user-images.githubusercontent.com/5435954/204153935-15f1ac58-fec3-4318-9939-052587995100.png)

**Comment by karlrahn** [comment]
I think I can remove the 2 in the middle, but I think that the bot won't be stiff enough, so I am thinking that I'll leave the other on both sides.

**Comment by karlrahn** [comment]
As the walls will only be connected from top plate.
