### ISSUE TITLE
Does the voltage converter PCB account for heatsinks?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#48]
Does your design account for heat sink sizes? Or is it just the PCB? The heat sinks stick out from the sides:

![image](https://user-images.githubusercontent.com/5435954/204154131-9d76f09d-7ee9-460a-ba2d-c70424319252.png)

![image](https://user-images.githubusercontent.com/5435954/204154145-d78bc7b0-114b-43dc-801f-948733290869.png)

**Comment by karlrahn** [comment]
Okay, I think it won't fit like that. Can I get some measurements for voltregulator from somewhere?

**Comment by karlrahn** [comment]
Changed the location for the mainboard and voltage regulator.

**Comment by karlrahn** [comment]
Now fits with heatsinks
