### ISSUE TITLE
[Mechanics] how do you do the sidewalls?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#5]
The sidewalls are 10mm thick, how do you plan to do them. 3D printing them can take a long time (over an hour a piece) but it can be milled much faster

You can split it to 2 4.8mm thick sheets that are bolted together in a few spots. Something like this:

![image](https://user-images.githubusercontent.com/5435954/194121979-41006683-af61-4a7d-a45d-dc26cc4ef009.png)

Same thing with the other side the motor spacer seems reasonable to print but the sliding surfaces can be done the same way. (This component is additionally hard to print because of overhangs)

**Comment by Akustav** [comment]
There is still some issues here. The main one is that it is difficult to understand how the thrower mounts using the side extrusions.
Are these holes supposed to align?

![image](https://user-images.githubusercontent.com/5435954/194743279-4a28ec68-acab-4520-abbe-12a1782fd80b.png)

I would suggest making the sidewalls and mounting posts as separate components that can be attached to each other. This would look something like this:

Red lines are the block and blue lines are holes through it that are used to mount it to the sidewall.
![image](https://user-images.githubusercontent.com/5435954/194743380-15fe1a26-d2d2-445d-84b4-a7434f84b8d8.png)


WDYT?

**Comment by karlrahn** [comment]
I asked, if we can dril some holes to the LeBot, and we were allowed when I asked Reiko. In general we will make new holes for the robot.

**Comment by karlrahn** [comment]
Made new pillars for walls, separated from walls. Full build will be made with printing with 3D printers, in total of 8 pieces. Some larger parts, like the ramps can be made with CNC.

**Comment by Akustav** [comment]
This solution seems a lot simpler to make. I would mill the sidewalls and internal ramps and 3D-rpint the pillars. 3D milled pieces should be 4.8mm thick.

**Comment by karlrahn** [comment]
I was thinking if the wall width can be made 4.5mm, because I saw that the stock version is 4.8mm

**Comment by karlrahn** [comment]
In general, probably I will be milling the walls with width of 4.5mm using 4.8 material
