### ISSUE TITLE
Tight radiuses on milled logos

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#50]
The current radius is 2mm. Maybe you can increase it to 1.5 so everything can be milled with a 3 mm mill? Less tool changes makes the work simpler.

![image](https://user-images.githubusercontent.com/5435954/204867755-32c13eec-54f5-4931-8341-16028cc6ca60.png)

**Comment by karlrahn** [comment]
will do!

**Comment by karlrahn** [comment]
All good! Fixed
