### ISSUE TITLE
Use wider tracks, polygons and multiple vias for higher currents

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#52]
![image](https://user-images.githubusercontent.com/1595938/204888721-1d8207eb-f7bb-4eb6-93b2-a4fdc788ee99.png)

0.254 mm wide track can carry about 1.7 A of current at 20 degrees temperature rise:
![image](https://user-images.githubusercontent.com/1595938/204888829-210c74d8-8243-4343-9676-dd53e17fb2c1.png)

Each motor driver is limited to about 3 A in the current design.

I don't think it's possible to carry 9 A of current with 0.254 mm wide track.

Motor driver inputs and outputs need to able to carry 3 A of current.

![image](https://user-images.githubusercontent.com/1595938/204889198-2328503e-1190-4008-9738-fe10812d7d09.png)

**Comment by ReikoR** [comment]
1. One via for battery input pads is not enough. Worst case current can be close to 10 A (3A per motor driver)
![image](https://user-images.githubusercontent.com/1595938/205431200-2204d94d-9a7a-4a7b-9ef8-9306073b04f1.png)

2. Connect motor driver output copper areas directly.
![image](https://user-images.githubusercontent.com/1595938/205431397-28e4d58d-978b-457e-918d-ec08c65a600e.png)

3. Use more vias to connect +16V to motor driver. Smaller (0.2/0.45 mm) vias can be used to be able to fit them better. Smaller vias inside pads also don't pull the solder away that much from the pad when soldering.
![image](https://user-images.githubusercontent.com/1595938/205431472-d3b7e709-26e3-4e38-a4e7-326ead6a57c9.png)

4. Make motor driver supply polygon as wide as possible for higher current capability and better thermal performance.
\
Current layout:
![image](https://user-images.githubusercontent.com/1595938/205431558-4b8111da-f17d-40b4-891f-d88572b74e55.png)
 \
 Proposed layout: 
![image](https://user-images.githubusercontent.com/1595938/205431752-a677f041-eac5-42af-8d52-d4a14ed638a0.png)

**Comment by ReikoR** [comment]
1. JLCPCB minimum via size is 0.2 mm hole / 0.45mm diameter.
\
From https://jlcpcb.com/capabilities/Capabilities:
_For Multi Layer PCB, the minimum via hole size is 0.2mm_
_For Multi Layer PCB, the minimum via diameter is 0.45mm_
\
![image](https://user-images.githubusercontent.com/1595938/205501403-09586b63-2b5f-45e1-bf53-25618fa2bcd6.png)

2. Don't place vias too close to each other.
\
From https://jlcpcb.com/capabilities/Capabilities:
_Hole to hole clearance(Different nets) 0.5mm_
\
![image](https://user-images.githubusercontent.com/1595938/205501903-dc07a253-b820-447d-bf91-1c11d16a20a7.png)

3. Avoid routing through polygons and creating gaps. Route more on the top layer.
\
![image](https://user-images.githubusercontent.com/1595938/205502082-0d1de53c-4f56-410b-be17-790a86cf0401.png)

4. More vias won't hurt, but microcontroller and isolators don't consume much current. Just to keep in mind when changing to correct via sizes.
![image](https://user-images.githubusercontent.com/1595938/205502309-0c90bf9d-9018-4373-9f96-0e33289fad3d.png)

**Comment by incrut** [comment]
Question about avoiding routing through polygons and creating gaps. Route more on the top layer.

Should I make those tracks smaller on the bottom side and route more on the top side, or do you mean it is necessary to delete all the routes on the bottom side and use only the top layer? If I cannot route on the bottom layer at all, I do not see any opportunity to connect some of the pins with each other, as they sometimes intersect, and I do not know what I should do in this case.

**Comment by ReikoR** [comment]
Route mostly on top layer and at the edge of the polygon.

Something like this:
![image](https://user-images.githubusercontent.com/1595938/205511384-c9ecb6d1-9d99-49f9-9ccb-517ffecce292.png)
![image](https://user-images.githubusercontent.com/1595938/205511455-c444b6f3-04c1-4ecc-bda0-027049827d45.png)

**Comment by ReikoR** [comment]
Some of the vias don't have nets:
![image](https://user-images.githubusercontent.com/1595938/205728635-1cc66f2b-b95b-4235-bb4d-3264b858d19e.png)

**Comment by incrut** [comment]
> Some of the vias don't have nets: ![image](https://user-images.githubusercontent.com/1595938/205728635-1cc66f2b-b95b-4235-bb4d-3264b858d19e.png)

Fixed that.
