### ISSUE TITLE
USB connector slot holes incorrect

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#67]
![image](https://user-images.githubusercontent.com/1595938/205503942-9facf668-ab91-462f-8fb6-61816d89c19c.png)

From [connector drawing](https://cdn.amphenol-cs.com/media/wysiwyg/files/drawing/10118193.pdf):
![image](https://user-images.githubusercontent.com/1595938/205504035-c09360f3-7ccc-4bae-ac50-97b0ca868063.png)

**Comment by incrut** [comment]
![image](https://user-images.githubusercontent.com/113035229/205505250-7d4393d2-a8b5-4c29-871a-6786d2fa1592.png)
So did I get it right, and it should look like this?

**Comment by ReikoR** [comment]
Yes
