### ISSUE TITLE
Mainboard documentation

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-jackbot#68]
1. _"This PCB is meant for driving 3 Polulu motors"_
\
It can drive other brushed DC motors also, not just Pololu motors.

2. _"The motor side will have 16.8V driving the motors with stall current of 5.5A for each motor. The motors can withstand 16.8V max and the motor drivers should be capable of limiting the current as well between the stall current and the power of 12W for each motor."_
\
_"motors can withstand 16.8V max"_
This is not correct.
\
Instead of all of this specify that the maximum recommended input voltage for motor drivers is 16.8V. It could be a higher, but motor driver capacitors used on the board have voltage rating of 25V and the supply voltage should be kept below that with some margin.
\
Also specify what is the output current limit that the drivers have been configured to.

3. Connector (programmer, encoders, thrower) pinouts are missing.

**Comment by karlrahn** [comment]
I think I fixed and added missing component pinouts to the doc.
