### ISSUE TITLE
[Mechanics] thrower motor center different from ramp center

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-jackbot#8]
Currently the motors center is higher than the ramps. Is this intentional?
![image](https://user-images.githubusercontent.com/5435954/194123360-ee06b0dc-7ae7-43da-937b-e671b9a1d04a.png)

**Comment by Akustav** [comment]
The issue persists: 
![image](https://user-images.githubusercontent.com/5435954/194742948-de6f712a-4019-4cc3-a898-ff06b7b771e6.png)

**Comment by karlrahn** [comment]
It is intentional

**Comment by karlrahn** [comment]
up
